### ISSUE TITLE
Unable to find reverse files

### ISSUE THREAD

**Issue by sherrinm** [tkluck/StatProfilerHTML.jl#11]
I'll looking to include StatProfileHTML as an alternate to the Profile/ProfileView method in the 2nd edition of my book on "Mastering Julia"

The one '_feature_' I got was on calling's statprofilehtml() I get a number of warning such as:

Unable to find reverse file for '/Users/osx/buildbot/slave/package_osx64/build/usr/share/julia/stdlib/v1.0/Random/src/Random.jl'

It seems unable to generate the additional HTML files from source in the STDLIB, all though it has not problems with ones in BASE

It is no big deal since the files: 

    index.html,  clickable_stacks_by_time.svg,  subs.html,  files.html

... are all generated OK and the others are on disk, but wondered if the Julia source can be modified to at least suppress (with a switch) or change the output.

Incidentiy - love the use of a Perl module as a backend

BTW: I'm running it on a Mac (OSX) which will probably affect where the files are located

Malcolm (Sherrington)

**Comment by tkluck** [comment]
Hey Malcolm! Thanks for flagging this issue.

We can easily suppress the warning by removing it from the perl code. The user will still see the issue when clicking the files, but arguably that's still a better experience. You think we should? I would be happy to make it so.

**Comment by tkluck** [comment]
This issue should have been solved in the current pure-Julia version. Closing.

**Comment by tautomer** [comment]
I still get the error

```text
Unable to find reverse file for '/build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Random/src/normal.jl'
Unable to find reverse file for '/build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Random/src/Random.jl'
Unable to find reverse file for '/build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/LinearAlgebra/src/matmul.jl'
Unable to find reverse file for '/build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Profile/src/Profile.jl'
Unable to find reverse file for '/build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Random/src/generation.jl'
Unable to find reverse file for '/build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/LinearAlgebra/src/blas.jl'
Unable to find reverse file for '/build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Random/src/RNGs.jl'
Unable to find reverse file for '/build/julia-98cBbp/julia-1.4.1+dfsg/usr/share/julia/stdlib/v1.4/Random/src/DSFMT.jl'
```

By `add StatProfilerHTML`, Julia installs version 1.1.0. [You said version 1.1 is fully Julia](https://github.com/tkluck/StatProfilerHTML.jl/issues/16#issuecomment-600229292). Did you forget to tag a release?

**Comment by pkofod** [comment]
Yeah I'm getting v1.0.0 as well

**Comment by tkluck** [comment]
What version of Julia are you using? It's possible that this is because of minimum compatibility being set to julia 1.3 ?

**Comment by tautomer** [comment]
> What version of Julia are you using? It's possible that this is because of minimum compatibility being set to julia 1.3 ?
> 
> edit: link: https://github.com/JuliaRegistries/General/blob/master/S/StatProfilerHTML/Compat.toml

I was using 1.4 and now 1.5. Both got 1.0.0 version of this package.

**Comment by tkluck** [comment]
Opened #17 for this follow-up issue. @tautomer or @pkofod, could you help me isolate the issue by checking what I wrote there?

**Comment by victorialena** [comment]
has this been solved?  running in the same error. not blocking anything just annoying :)

**Comment by tkluck** [comment]
Yes this has been resolved in the latest version. Have a look at #17 for how to see what's keeping you on an older version.

**Comment by rickbeeloo** [comment]
I also got this with 1.8 and the lastest version of StatProfilerHTML:
```
Unable to find reverse file for '/cache/build/default-amdci4-6/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/REPL/src/REPL.jl'
ERROR: KeyError: key 0x0000000000000001 not found
```
